---
- name: Add repo key
  apt_key:
    url: http://archive.getdeb.net/getdeb-archive.key
  when: ansible_os_family == "Debian"

- name: add repository
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "http://archive.getdeb.net/ubuntu {{ ansible_distribution_release }}-getdeb apps"
  when: ansible_os_family == "Debian"
